spring:
  datasource:
    url: jdbc:mysql://192.168.13.140:3306/mysql?characterEncoding=utf-8&&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    name: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
girl:
  name: das
  age: 23
